version: '3.1'

services:
    mongodb:
        image: mongo:latest
        restart: always
        networks:
            - ito_net
        ports:
            - 27017:27017

    api-download:
        depends_on:
            - mongodb
        image: ito/api-download:latest
        restart: always
        networks:
            - ito_net
        ports:
            - 5000:5000
        environment:
            - MONGO_URI=mongodb://mongodb:27017
            
    api-upload:
        depends_on:
            - mongodb
        image: ito/api-upload:latest
        restart: always
        networks:
            - ito_net
        ports:
            - 5001:5001
        environment:
            - MONGO_URI=mongodb://mongodb:27017

networks: 
    ito_net: