version: '3.1'

services:
    mongo:
        image: mongo:latest
        restart: always
        networks:
            - ito_net
        ports:
            - 27017:27017

    api-download:
        image: ito/api-download:latest
        restart: always
        networks:
            - ito_net
        ports:
            - 5000:5000
        depends_on:
            - mongo

    api-upload:
        image: ito/api-upload:latest
        restart: always
        networks:
            - ito_net
        ports:
            - 5001:5001
        depends_on:
            - mongo

networks: 
    ito_net: